import { Target, Lightbulb, Zap, User, Search, TrendingUp } from "lucide-react";

export default function Reports() {
  return (
    <div className="animate-in">
      <h1>Harness Reports</h1>
      <p className="subtitle">AI改善ループによるインサイトと戦略の進化履歴</p>

      <div style={{ marginTop: '32px' }}>
        <div className="card delay-1">
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '24px', borderBottom: '1px solid var(--border-color)', paddingBottom: '16px' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '16px' }}>
              <div style={{ background: 'var(--accent-primary)', padding: '8px 12px', borderRadius: '8px', color: 'white', fontWeight: 600 }}>
                v1.0
              </div>
              <div>
                <h2 style={{ margin: 0, fontSize: '1.4rem' }}>Report #001: 「デトックス失敗のメカニズム」とインサイト発掘</h2>
                <span style={{ fontSize: '0.85rem', color: 'var(--text-secondary)' }}>Generated by AI Harness Loop - 2026/07/09</span>
              </div>
            </div>
            <span className="badge" style={{ background: 'rgba(16, 185, 129, 0.1)', color: '#10b981' }}>Completed</span>
          </div>

          <div style={{ display: 'flex', flexDirection: 'column', gap: '32px' }}>
            
            {/* Section 1: AI Brainstorming - The Excuses */}
            <section>
              <h3 style={{ display: 'flex', alignItems: 'center', gap: '8px', color: 'var(--accent-primary)', marginBottom: '16px' }}>
                <Search size={20} />
                1. なぜ制限を破るのか？（心の中の言い訳）
              </h3>
              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))', gap: '16px' }}>
                <div style={{ background: 'rgba(255,255,255,0.03)', padding: '16px', borderRadius: '8px', borderLeft: '4px solid #ef4444' }}>
                  <h4 style={{ margin: '0 0 8px 0', display: 'flex', alignItems: 'center', gap: '8px' }}>
                    <span style={{ fontSize: '1.2rem' }}>🤔</span> 生産性の錯覚（Productivity Illusion）
                  </h4>
                  <p style={{ margin: 0, fontSize: '0.9rem', color: 'var(--text-secondary)', lineHeight: '1.6' }}>
                    「仕事/大学の大事な連絡が来ているかもしれない」「ニュースだけチェックしよう」など、娯楽ではなく**『生産的な理由』を無意識にでっち上げ**、ルールを破る行為を正当化してしまう。
                  </p>
                </div>
                <div style={{ background: 'rgba(255,255,255,0.03)', padding: '16px', borderRadius: '8px', borderLeft: '4px solid #f59e0b' }}>
                  <h4 style={{ margin: '0 0 8px 0', display: 'flex', alignItems: 'center', gap: '8px' }}>
                    <span style={{ fontSize: '1.2rem' }}>😰</span> 見逃し不安（FOMO）
                  </h4>
                  <p style={{ margin: 0, fontSize: '0.9rem', color: 'var(--text-secondary)', lineHeight: '1.6' }}>
                    制限時間が長くなるほど「自分だけが話題に取り残されていないか」という孤独感や焦燥感が募り、通知が来ていなくても自ら確認しにいってしまう。
                  </p>
                </div>
              </div>
            </section>

            {/* Section 2: AI Brainstorming - Unconscious Triggers */}
            <section>
              <h3 style={{ display: 'flex', alignItems: 'center', gap: '8px', color: 'var(--accent-primary)', marginBottom: '16px' }}>
                <Target size={20} />
                2. 無意識にスマホを触る瞬間（トリガー）
              </h3>
              <ul style={{ background: 'rgba(255,255,255,0.02)', padding: '20px 20px 20px 40px', borderRadius: '8px', margin: 0, color: 'var(--text-secondary)', lineHeight: '2' }}>
                <li><strong>マイクロ・ボアダム（微小な退屈）:</strong> 電子レンジを待つ数十秒、エレベーターの中、信号待ちなど、脳が「ほんの少しの空白」に耐えられなくなった瞬間。</li>
                <li><strong>タスクのトランジション（切り替え）:</strong> 「勉強が終わった瞬間」「お風呂に入る直前」「朝起きてすぐ」など、次の行動へ移る前の”バッファ（緩衝材）”としてスマホに逃避する。</li>
                <li><strong>感情の揺れ:</strong> 疲れた、少しイライラした、というネガティブな感情を「手軽なドーパミン」で即座に中和しようとする防衛本能。</li>
              </ul>
            </section>

            {/* Section 3: Harness Loop Conclusion */}
            <section style={{ background: 'var(--bg-glass)', border: '1px solid var(--accent-primary)', padding: '24px', borderRadius: '12px' }}>
              <h3 style={{ display: 'flex', alignItems: 'center', gap: '8px', color: 'var(--text-primary)', marginBottom: '16px' }}>
                <Zap size={20} color="var(--accent-primary)" />
                3. バージョン1 インサイトと戦略の進化（Harness Loop）
              </h3>
              <p style={{ fontSize: '1rem', lineHeight: '1.8', color: 'var(--text-secondary)', margin: '0 0 16px 0' }}>
                これらのAI分析から、既存の制限アプリが失敗する根本原因は**「ただスマホをブロックするだけで、ユーザーの『不安』や『退屈』という感情の隙間を埋めてくれないから」**だと導き出されます。
              </p>
              <div style={{ padding: '16px', background: 'rgba(59, 130, 246, 0.1)', borderRadius: '8px' }}>
                <h4 style={{ margin: '0 0 8px 0', color: 'var(--accent-primary)' }}>💡 コンセプトの進化（ジャンプ）</h4>
                <p style={{ margin: 0, fontSize: '0.95rem', lineHeight: '1.7' }}>
                  「推しからの応援」アプローチは、単なるブロック機能ではなく、**「退屈や不安を『推しとの連帯感』で上書きする感情のセーフティーネット」**として機能させるべきです。<br/><br/>
                  ユーザーが言い訳を作ってスマホを開こうとした瞬間、強制終了するのではなく、推しが<strong>「今、私も頑張ってるとこ！一緒に耐えよ！」</strong>と語りかけることで、FOMO（見逃し不安）をJOMO（見逃す喜び・推しとの共有時間）に反転させる体験が、BranCo!での強力な評価軸（革新性）になります。
                </p>
              </div>
            </section>

          </div>
        </div>
      </div>
    </div>
  );
}
